name: CI

on:
- push
- pull_request
- workflow_dispatch

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby-jruby
      min_version: 2.7

  host:
    needs: ruby-versions
    name: ${{ matrix.os }} ${{ matrix.ruby }} ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    env:
      BUNDLE_WITHOUT: release
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        env:
          - ""
        include:
          - { os: ubuntu-latest  , ruby: debug }
          - { os: ubuntu-latest  , ruby: asan }
          - { os: ubuntu-24.04-arm, ruby: 3.4 }
          - { os: ubuntu-latest  , ruby: 3.4, env: "JSON_DISABLE_SIMD=1" }
          - { os: ubuntu-latest  , ruby: 3.4, env: "JSON_DEBUG=1" }
          - { os: macos-14, ruby: 3.4 }
          - { os: windows-latest , ruby: mswin     } # ruby/ruby windows CI
          - { os: macos-latest  , ruby: jruby-9.4 } # Ruby 3.1
          - { os: ubuntu-latest  , ruby: jruby-9.4 } # Ruby 3.1
          - { os: macos-latest   , ruby: truffleruby }
          - { os: ubuntu-latest  , ruby: truffleruby }
        exclude:
          - { os: windows-latest, ruby: jruby }

    steps:
      - uses: actions/checkout@v7

      - name: Set up Ruby
        uses: ruby/setup-ruby-pkgs@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}

      - run: bundle exec rake compile ${{ matrix.env }}

      - run: bundle exec rake test JSON_COMPACT=1 ${{ matrix.env }}

      - run: bundle exec rake build

      - run: gem install pkg/*.gem
        if: ${{ matrix.ruby != '3.2' }}

  valgrind:
    name: Ruby memcheck
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v7

      - name: Set up Ruby
        uses: ruby/setup-ruby-pkgs@v1
        with:
          bundler-cache: true
          ruby-version: "3.3"
          apt-get: valgrind

      - run: bundle exec rake compile

      - run: bundle exec rake valgrind JSON_COMPACT=1
